name: time_imputation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pytorch-cuda=12.1
  - pytorch=2.5.1
  - tensorboard
  - xarray
  - hdf5
  - glasbey
  - matplotlib
  - pandas
  - scipy
  - numpy
  - seaborn
  - scikit-learn
  - cartopy
  - plotly
  - gsw
  - pyqt
  - ipython
  - tqdm
  - geopy
  - datetimerange
  - netcdf4
  - scikit-gstat
  - xskillscore
  - haversine
  - pandas-stubs=2.3.2.250926
  - gstools
  - esda
  - xarray-spatial
  - kneed
  - pip
  - pip:
      git+https://github.com/dnowacki-usgs/missingpy.git
